jwt:
  secret: ${JWT_SECRET:bXktand0U2VjcmV0LWZvci1sb2NhbC1wb3J0dWdhbC1saXNib2EtMjAyNg==}
  expiration-ms: ${JWT_EXPIRATION_MS:120000}
auth:
  allowed-client-ids: ${ALLOWED_CLIENT_IDS:client-user-01,client-admin-01}
  admin-client-ids: ${ADMIN_CLIENT_IDS:client-admin-01}

