server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: ${DB_URL}
jwt:
  secret: ${JWT_SECRET}
clients:
  user-service:
    base-url: ${USER_SERVICE_URL}
